### ISSUE TITLE
Plugin throwing a Python error. Assuming QgsRasterLayer target data?

### ISSUE THREAD

**Issue by sdnxgr** [josemamira/DotMap#1]
Hi and thanks for the plugin.

Running QGIS 3.4 on Win7, 64bit.
Getting error on plugin execution:

2019-10-09T13:54:52     WARNING    Traceback (most recent call last):
              File "C:/Users/Owner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DotMap\dot_map.py", line 206, in run
              if layer.geometryType() == 2: #2=poligonos
             AttributeError: 'QgsRasterLayer' object has no attribute 'geometryType'

I'm not familiar with Python enough to diagnose, but it looks like it's assuming a raster is the target dataset, which makes no sense. Tried it with polygon data highlighted/selected, and in editing and non-editing modes which also shouldn't matter.
Any help is appreciated.

**Comment by josemamira** [comment]
Thanks for share this bug

Replace this lines (line 205 and above)

        for layer in QgsProject.instance().mapLayers().values():
            if layer.geometryType() == 2: #2=poligonos
                layer_list.append(layer.name())
                self.dlg.layerComboBox.addItem(layer.name())

With this new code

        for layer in QgsProject.instance().mapLayers().values():

*            layerType = layer.type()            if layerType ==
QgsMapLayer.VectorLayer:*
                if layer.geometryType() == 2: #2=poligonos
                    layer_list.append(layer.name())
                    self.dlg.layerComboBox.addItem(layer.name())

I think I solve it with this little code
I make a new version and upload to Qgis

Tested in Qgis 3.8 in Ubuntu 18.04

Regards
Jose

**Comment by sdnxgr** [comment]
Yep, that works, thank you!
